version: '3'

services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    hostname: rabbitmq
    networks:
      - mynetwork
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "rabbitmq", "5672" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  db:
    image: postgres:16.2
    hostname: db
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_PASSWORD=asyncjobs@123
      - POSTGRES_USER=asyncjobs
      - POSTGRES_DB=asyncjobs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  publisher:
    networks:
      - mynetwork
    hostname: publisher
    build: 
      dockerfile: ./Dockerfile
      args:
        - PATH_DIR=publisher
    ports:
      - "8080:8080"
    environment:
      - DB_PASSWORD=asyncjobs@123
      - DB_USER=asyncjobs
      - DB_NAME=asyncjobs
      - DB_PORT=5432
      - DB_HOST=db
      - RABBITMQ_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    networks:
      - mynetwork
    build: 
      dockerfile: ./Dockerfile
      args:
        - PATH_DIR=consumer
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672/
      - DB_PASSWORD=asyncjobs@123
      - DB_USER=asyncjobs
      - DB_NAME=asyncjobs
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  k6:
    image: loadimpact/k6:latest
    hostname: k6
    networks:
      - mynetwork
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - k6_URL=http://api:8080
    volumes:
      - ./test/load-test/tests:/scripts

  grafana:
    image: grafana/grafana:latest
    networks:
      - mynetwork
    hostname: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./test/load-test/dashboards:/var/lib/grafana/dashboards
      - ./test/load-test/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./test/load-test/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  influxdb:
    image: influxdb:1.8
    hostname: influxdb
    networks:
      - mynetwork
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
networks:
  mynetwork: