name: Golang-async-jobs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build publisher 
      run: go build -v ./internal/publisher

    - name: Build Consumer
      run: go build -v ./internal/consumer

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate Sha
      id: generate_sha
      run : |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
    
    - name: Build docker image from publisher
    run: docker build --build-arg PATH_DIR=publisher -t lucssdev2005/publisher:${{steps.generate_sha.outputs.sha}} .
    
    - name: Build docker image from consumer
    run: docker build --build-arg PATH_DIR=consumer -t lucssdev2005/publisher:${{steps.generate_sha.outputs.sha}} .

    - name: docker Login
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

    - name: publish docker image from 'publisher'
    run: docker push lucssdev2005/publisher:${{steps.generate_sha.outputs.sha}}
    